version: '3'
services:
  identity-server:
    extends:
     file: identityserver-service.yml
     service: identity-server
  webapi:
    extends:
     file: webapi-service.yml
     service: webapi    
  cp-zookeeper:
    image: confluentinc/cp-zookeeper:latest
    restart: on-failure
    container_name: cp-zookeeper
    hostname: cp-zookeeper
    networks: 
      - broker-kafka
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  cp-broker-1:
    image: confluentinc/cp-kafka:latest
    restart: on-failure
    container_name: cp-broker-1
    hostname: cp-broker-1
    networks: 
      - broker-kafka
    depends_on:
      - cp-zookeeper
    extra_hosts:
      - 'moby:127.0.0.1'
      - 'localhost: 127.0.0.1'
    ports:
      - 9091:9091
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLED: 'true'
      KAFKA_CONFLUENT_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      KAFKA_NUMBER_PARTITIONS: 1  
  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    container_name: kafdrop
    hostname: kafdrop
    networks:    
      - broker-kafka
    depends_on:
      - cp-broker-1
    ports:
      - 19000:9000
    environment:
      KAFKA_BROKERCONNECT: broker-1:29092
  mysql:
    image: mysql/mysql-server
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Moorthi@16
    ports:
      - "1433:1433"
    volumes:
      - C:\Users\91978\Owen\DockerVolumes\sqlserver:/var/opt/mssql/data 
  seq:
    image: datalust/seq:latest
    ports:
      - 117:117
      - 5341:5341
    environment:
     - ACCEPT_EULA=Y

volumes:
  db-data:
  app-data:
networks: 
  broker-kafka:
    driver: bridge  


